# Site settings
title: Pharo Catalog
email: noreply@pharo.org
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://pharo-compendium.github.io/" # the base hostname & protocol for your site
twitter_username: pharoproject
github_username:  pharo-compendium

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Pharo

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext